x=msgbox("Hi Its me Aidyn", 0+32, ":)")
x=msgbox("So Ok bye", 0+32, ":)")
x=msgbox("iM GoNnA HHACK YOUR PC :::::::>:)", 0+16, ";'[l'\p[;")
x=msgbox("Just kidding :)", 0+32, ":I")
x=msgbox("If You play Cs 2", 0+32, ":)")
x=msgbox("Really", 0+32, ":O")
x=msgbox("YOU LYING", 0+16, "[][[]P'\;][;'\P[];][\'")
x=msgbox("]]J]'T]D\]J\RT]", 0+16, "[][[]P'\;][;'\P[];][\'")
x=msgbox("https://youtu.be/CRORiWw9iBU?si=NeqKMv0U5myj-YU2&t=79", 0+16, "[][[]P'\;][;'\P[];][\'")
